DROP TABLE IF EXISTS WIDGETS;
  
CREATE TABLE WIDGETS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  X INT NOT NULL,
  Y INT NOT NULL,
  width INT NOT NULL,
  height INT NOT NULL,
  z_index INT NOT NULL,
  modify_date TIMESTAMP  DEFAULT NULL
);